package io.github.clamentos.blackhole.framework.implementation.utility;

import java.sql.SQLException;

import io.github.clamentos.blackhole.framework.scaffolding.exceptions.PersistenceException;

public final class SqlExceptionDecoder {
    
    public static PersistenceException decode(String message, SQLException exc) {

        //TODO
        return(new PersistenceException("(dummy exception generated by SqlExceptionDecoder.decode) -> sql message: " + exc.getMessage()));
    }
}
