package io.github.clamentos.blackhole.framework.implementation.utility.exportable;

///
import io.github.clamentos.blackhole.framework.scaffolding.exceptions.PersistenceException;

///.
import java.sql.SQLException;

///
/**
 * <h3>Sql Exception Decoder</h3>
 * Utility class to decode SQL exceptions into persistence exceptions.
*/
public final class SqlExceptionDecoder {

    ///
    /**
     * Generates the appropriate persistence exception based on the provided SQL exception.
     * @param message : The exception message.
     * @param exc : The SQL exception to decode.
     * @return The never {@code null} decoded persistence exception.
    */
    public static PersistenceException decode(String message, SQLException exc) {

        //TODO
        return(new PersistenceException("(dummy exception generated by SqlExceptionDecoder.decode) -> sql message: " + exc.getMessage()));
    }

    ///
}
